version: '3.7'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: finki_rasporedi
      MYSQL_USER: admin
      MYSQL_PASSWORD: ogan123
      MYSQL_ROOT_PASSWORD: ogan123
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: