namespace FinkiRasporedi.Models.Enums
{
    public enum ProfessorTitle
    {
        TUTOR, TEACHING_ASSISTANT,
        ASSISTANT_PROFESSOR, ASSOCIATE_PROFESSOR, PROFESSOR, RETIRED,
        ELECTED_ASSISTANT_PROFESSOR, ELECTED_ASSOCIATE_PROFESSOR, ELECTED_PROFESSOR,
        EXTERNAL_EXPER
    }
}
