name: Docker Image CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker backend
      run: docker build ./dotnet --file ./dotnet/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/aws-backend-healthy:latest 

    - name: Build Docker frontend
      run: docker build ./flutter --file ./flutter/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/flutter-frontend:latest

    - name: Push Docker image 1
      run: docker push ${{ secrets.DOCKER_USERNAME }}/aws-backend-healthy:latest 

    - name: Push Docker image 2
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flutter-frontend:latest
